services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    privileged: true
    shm_size: "256mb"
    depends_on:
      - mosquitto
    ports:
      - "127.0.0.1:5000:5000"   # Frigate UI
      - "8554:8554"   # RTSP restream, optional but useful
      - "8555:8555/tcp"
      - "8555:8555/udp"
    volumes:
      - ./frigate/config:/config
      - ./frigate/storage:/media/frigate
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      - TZ=${TZ}
      - FRIGATE_RTSP_PASSWORD=change_this_later
      - FRIGATE_REOLINK_USER=${FRIGATE_REOLINK_USER}
      - FRIGATE_REOLINK_PASSWORD=${FRIGATE_REOLINK_PASSWORD}
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:2.7.2
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - TZ=${TZ}
    restart: unless-stopped

  emdc-mqtt-writer:
    build:
      context: ${EMDC_BACKEND_PATH}
      dockerfile: Dockerfile
    container_name: emdc-mqtt-writer
    depends_on:
      - mosquitto
    volumes:
      - ./emdc_mqtt_writer/state:/app/state
    environment:
      - TZ=${TZ}
    restart: unless-stopped
